swagger: '2.0'

info:
  title: Benru API
  version: "0.1.0"

paths:
  /pullrequest/merged:
    post:
      x-swagger-router-controller: gm_analytics
      operationId: handlers.buildimage
      summary: Update packages in mirror server.
      responses:
        200:
          description: Successful response.
          schema:
            type: object
            properties:
              response:
                type: string
                description: Pull request merged

